# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # For testing the Solidity code
  test-solidity:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: begeisti/ganache-truffle5
    steps:
      - uses: actions/checkout@v2
      # Runs a single command using the runners shell
      - name: Install project dependencies
        run: yarn
      - name: Test Solidity code
        run: truffle test --network docker_ganache
