name: CI

on:
  push:
    branches: [ master ]

jobs:
  # Since GitHub Actions does not support caching between jobs properly, all CI steps are put into one job.
  # TODO:: Check caching later!
  verify-solidity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install project dependencies
        run: yarn --frozen-lockfile --prefer-offline
      - name: Checking the format of Solidity files
        run: yarn check:format:solidity
      - name: Lint check of Solidity files
        run: yarn lint:solidity
      - name: Test Solidity code
        run: yarn test:solidity