name: CI

on:
  push:
    branches: [ master ]

jobs:
  # Since GitHub Actions does not support caching between jobs properly, all CI steps are put into one job.
  # TODO:: Check caching later!
  verify-solidity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Install project dependencies
        run: yarn --frozen-lockfile
      - name: Checking the format of Solidity files
        run: yarn check:format:solidity
      - name: Lint check of Solidity files
        run: yarn lint:solidity
      - name: Install truffle v5.1.51
        run: npm install --unsafe-perm -g truffle@5.1.51
      - name: Test Solidity code
        run: truffle test